(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var f="function",k="string",l,n=this||self,p=function(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length};var q=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(typeof a===k)return typeof b!==k||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},r=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a===k?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},t=function(a){return Array.prototype.concat.apply([],
arguments)},u=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var v;a:{var w=n.navigator;if(w){var x=w.userAgent;if(x){v=x;break a}}v=""}var y=function(a){return-1!=v.indexOf(a)};var z=function(){};z.prototype.K=function(){return this};(new z).K("");var A=function(){};A.prototype.K=function(){return this};(new A).K("");var B=y("Trident")||y("MSIE");var C=function(a,b){return typeof b===k?a.getElementById(b):b},D=function(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var g=d=0,h;h=b[g];g++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(g=d=0;h=b[g];g++){e=h.className;var m;if(m=typeof e.split==f)m=0<=q(e.split(/\s+/),
c);m&&(a[d++]=h)}a.length=d;return a}return b};var E=function(a){this.I=a};E.prototype.serialize=function(a){var b=[];this.M(a,b);return b.join("")};
E.prototype.M=function(a,b){if(null==a)b.push("null");else{if("object"==typeof a){if(Array.isArray(a)){this.serializeArray(a,b);return}if(a instanceof String||a instanceof Number||a instanceof Boolean)a=a.valueOf();else{this.ia(a,b);return}}switch(typeof a){case k:this.Y(a,b);break;case "number":this.ha(a,b);break;case "boolean":b.push(String(a));break;case f:b.push("null");break;default:throw Error("Unknown type: "+typeof a);}}};
var F={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},G=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;E.prototype.Y=function(a,b){b.push('"',a.replace(G,function(c){var d=F[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),F[c]=d);return d}),'"')};E.prototype.ha=function(a,b){b.push(isFinite(a)&&!isNaN(a)?String(a):"null")};
E.prototype.serializeArray=function(a,b){var c=a.length;b.push("[");for(var d="",e=0;e<c;e++)b.push(d),d=a[e],this.M(this.I?this.I.call(a,String(e),d):d,b),d=",";b.push("]")};E.prototype.ia=function(a,b){b.push("{");var c="",d;for(d in a)if(Object.prototype.hasOwnProperty.call(a,d)){var e=a[d];typeof e!=f&&(b.push(c),this.Y(d,b),b.push(":"),this.M(this.I?this.I.call(a,d,e):e,b),c=",")}b.push("}")};var H="StopIteration"in n?n.StopIteration:{message:"StopIteration",stack:""},I=function(){};I.prototype.next=function(){throw H;};I.prototype.Z=function(){return this};var J=function(a,b){this.h={};this.c=[];this.H=this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};l=J.prototype;l.V=function(){return this.a};l.j=function(){this.B();for(var a=[],b=0;b<this.c.length;b++)a.push(this.h[this.c[b]]);return a};l.o=function(){this.B();return this.c.concat()};l.C=function(a){return K(this.h,a)};
l.equals=function(a,b){if(this===a)return!0;if(this.a!=a.V())return!1;b=b||L;this.B();for(var c,d=0;c=this.c[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};var L=function(a,b){return a===b};l=J.prototype;l.isEmpty=function(){return 0==this.a};l.clear=function(){this.h={};this.H=this.a=this.c.length=0};l.remove=function(a){return K(this.h,a)?(delete this.h[a],this.a--,this.H++,this.c.length>2*this.a&&this.B(),!0):!1};
l.B=function(){if(this.a!=this.c.length){for(var a=0,b=0;a<this.c.length;){var c=this.c[a];K(this.h,c)&&(this.c[b++]=c);a++}this.c.length=b}if(this.a!=this.c.length){var d={};for(b=a=0;a<this.c.length;)c=this.c[a],K(d,c)||(this.c[b++]=c,d[c]=1),a++;this.c.length=b}};l.get=function(a,b){return K(this.h,a)?this.h[a]:b};l.set=function(a,b){K(this.h,a)||(this.a++,this.c.push(a),this.H++);this.h[a]=b};
l.addAll=function(a){if(a instanceof J)for(var b=a.o(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};l.forEach=function(a,b){for(var c=this.o(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};l.clone=function(){return new J(this)};l.Z=function(a){this.B();var b=0,c=this.H,d=this,e=new I;e.next=function(){if(c!=d.H)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw H;var g=d.c[b++];return a?g:d.h[g]};return e};
var K=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var M=function(a){if(a.j&&typeof a.j==f)return a.j();if(typeof a===k)return a.split("");if(p(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},N=function(a,b,c){if(a.forEach&&typeof a.forEach==f)a.forEach(b,c);else if(p(a)||typeof a===k)r(a,b,c);else{if(a.o&&typeof a.o==f)var d=a.o();else if(a.j&&typeof a.j==f)d=void 0;else if(p(a)||typeof a===k){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else for(g in d=[],e=0,a)d[e++]=g;e=M(a);g=e.length;
for(var h=0;h<g;h++)b.call(c,e[h],d&&d[h],a)}};var aa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,ba=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var O=function(a,b){this.D=this.G=this.s="";this.A=null;this.F=this.L="";this.f=this.ga=!1;var c;a instanceof O?(this.f=void 0!==b?b:a.f,this.T(a.s),this.U(a.G),this.N(a.D),this.R(a.A),this.setPath(a.getPath()),this.S(a.g.clone()),this.O(a.F)):a&&(c=String(a).match(aa))?(this.f=!!b,this.T(c[1]||"",!0),this.U(c[2]||"",!0),this.N(c[3]||"",!0),this.R(c[4]),this.setPath(c[5]||"",!0),this.S(c[6]||"",!0),this.O(c[7]||"",!0)):(this.f=!!b,this.g=new P(null,this.f))};l=O.prototype;
l.toString=function(){var a=[],b=this.s;b&&a.push(Q(b,R,!0),":");var c=this.D;if(c||"file"==b)a.push("//"),(b=this.G)&&a.push(Q(b,R,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.A,null!=c&&a.push(":",String(c));if(c=this.getPath())this.J()&&"/"!=c.charAt(0)&&a.push("/"),a.push(Q(c,"/"==c.charAt(0)?ca:da,!0));(c=this.W())&&a.push("?",c);(c=this.F)&&a.push("#",Q(c,ea));return a.join("")};
l.resolve=function(a){var b=this.clone(),c=a.ea();c?b.T(a.s):c=a.fa();c?b.U(a.G):c=a.J();c?b.N(a.D):c=a.ca();var d=a.getPath();if(c)b.R(a.A);else if(c=a.X()){if("/"!=d.charAt(0))if(this.J()&&!this.X())d="/"+d;else{var e=b.getPath().lastIndexOf("/");-1!=e&&(d=b.getPath().substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],h=0;h<e.length;){var m=e[h++];"."==m?d&&h==e.length&&g.push(""):".."==m?((1<g.length||
1==g.length&&""!=g[0])&&g.pop(),d&&h==e.length&&g.push("")):(g.push(m),d=!0)}d=g.join("/")}else d=e}c?b.setPath(d):c=a.da();c?b.S(a.g.clone()):c=a.ba();c&&b.O(a.F);return b};l.clone=function(){return new O(this)};l.T=function(a,b){this.l();if(this.s=b?S(a,!0):a)this.s=this.s.replace(/:$/,"");return this};l.ea=function(){return!!this.s};l.U=function(a,b){this.l();this.G=b?S(a):a;return this};l.fa=function(){return!!this.G};l.N=function(a,b){this.l();this.D=b?S(a,!0):a;return this};l.J=function(){return!!this.D};
l.R=function(a){this.l();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.A=a}else this.A=null;return this};l.ca=function(){return null!=this.A};l.getPath=function(){return this.L};l.setPath=function(a,b){this.l();this.L=b?S(a,!0):a;return this};l.X=function(){return!!this.L};l.da=function(){return""!==this.g.toString()};l.S=function(a,b){this.l();a instanceof P?(this.g=a,this.g.P(this.f)):(b||(a=Q(a,fa)),this.g=new P(a,this.f));return this};l.W=function(){return this.g.toString()};
l.getQuery=function(){return this.W()};l.ja=function(a,b){this.l();this.g.set(a,b);return this};l.aa=function(a){return this.g.get(a)};l.O=function(a,b){this.l();this.F=b?S(a):a;return this};l.ba=function(){return!!this.F};l.removeParameter=function(a){this.l();this.g.remove(a);return this};l.l=function(){if(this.ga)throw Error("Tried to modify a read-only Uri");};l.P=function(a){this.f=a;this.g&&this.g.P(a);return this};
var S=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Q=function(a,b,c){return typeof a===k?(a=encodeURI(a).replace(b,ha),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},ha=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},R=/[#\/\?@]/g,da=/[#\?:]/g,ca=/[#\?]/g,fa=/[#\?@]/g,ea=/#/g,P=function(a,b){this.a=this.b=null;this.m=a||null;this.f=!!b};l=P.prototype;
l.i=function(){if(!this.b&&(this.b=new J,this.a=0,this.m)){var a=this;ba(this.m,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)})}};l.V=function(){this.i();return this.a};l.add=function(a,b){this.i();this.v();a=this.u(a);var c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.a+=1;return this};l.remove=function(a){this.i();a=this.u(a);return this.b.C(a)?(this.v(),this.a-=this.b.get(a).length,this.b.remove(a)):!1};l.clear=function(){this.v();this.b=null;this.a=0};
l.isEmpty=function(){this.i();return 0==this.a};l.C=function(a){this.i();a=this.u(a);return this.b.C(a)};l.forEach=function(a,b){this.i();this.b.forEach(function(c,d){r(c,function(e){a.call(b,e,d,this)},this)},this)};l.o=function(){this.i();for(var a=this.b.j(),b=this.b.o(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};l.j=function(a){this.i();var b=[];if(typeof a===k)this.C(a)&&(b=t(b,this.b.get(this.u(a))));else{a=this.b.j();for(var c=0;c<a.length;c++)b=t(b,a[c])}return b};
l.set=function(a,b){this.i();this.v();a=this.u(a);this.C(a)&&(this.a-=this.b.get(a).length);this.b.set(a,[b]);this.a+=1;return this};l.get=function(a,b){if(!a)return b;a=this.j(a);return 0<a.length?String(a[0]):b};l.setValues=function(a,b){this.remove(a);0<b.length&&(this.v(),this.b.set(this.u(a),u(b)),this.a+=b.length)};
l.toString=function(){if(this.m)return this.m;if(!this.b)return"";for(var a=[],b=this.b.o(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.j(d);for(var g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.m=a.join("&")};l.v=function(){this.m=null};l.clone=function(){var a=new P;a.m=this.m;this.b&&(a.b=this.b.clone(),a.a=this.a);return a};l.u=function(a){a=String(a);this.f&&(a=a.toLowerCase());return a};
l.P=function(a){a&&!this.f&&(this.i(),this.v(),this.b.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.setValues(d,b))},this));this.f=a};l.extend=function(a){for(var b=0;b<arguments.length;b++)N(arguments[b],function(c,d){this.add(d,c)},this)};var U=function(a,b,c){a:{var d=9==b.nodeType?b:b.ownerDocument||b.document;if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(b,null))){d=d[a]||d.getPropertyValue(a)||"";break a}d=""}d=d||(b.currentStyle?b.currentStyle[a]:null)||b.style&&b.style[a];return null==d||"inherit"==d||"transparent"==d||"rgba(0, 0, 0, 0)"==d?b!=(9==b.nodeType?b:b.ownerDocument||b.document).body&&b.parentNode?T(a,b.parentNode):c:d},T=function(a,b){return U(a,b,"rgb(0, 0, 0)")},ja=function(){for(var a=
D(document,"iframe","blogger-iframe-colorize",void 0),b=0;b<a.length;b++){var c=a[b],d=C(document,c.id+"-src"),e=d.href;if(!(new O(e)).aa("skin")){var g=T("color",c),h=T("backgroundColor",c),m=U("fontFamily",c,"serif");d.href="https://www.blogger.com/unvisited-link-"+(new Date).valueOf();var ia=T("color",d);d=d.href=e;e=encodeURIComponent;g=(new E(void 0)).serialize({color:g,backgroundColor:h,unvisitedLinkColor:ia,fontFamily:m});e=d+("#"+e(g))}c.src=e}};var ka=!B&&!(y("Safari")&&!((y("Chrome")||y("CriOS"))&&!y("Edge")||y("Coast")||y("Opera")||y("Edge")||y("Edg/")||y("OPR")||y("Firefox")||y("FxiOS")||y("Silk")||y("Android")));var V=-1;var W=function(){V=Math.floor(1E7*Math.random());for(var a=D(document,"iframe","blogger-comment-from-post",void 0),b=0;b<a.length;b++){var c=C(document,a[b].id+"-src"),d=new O(c.href);d.ja("blogspotRpcToken",V);c.href=d.toString()}ja();a=function(e){if(typeof e.data===k&&0==e.data.indexOf("set-comment-editor-height")){var g=document.getElementById("comment-editor");g.height=e.data.substring(26);if(ka&&g.dataset)g.dataset.resized=!0;else{if(/-[a-z]/.test("resized"))throw Error("");g.setAttribute("data-"+
"resized".replace(/([A-Z])/g,"-$1").toLowerCase(),!0)}}};window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)},X=["BLOG_CMT_createIframe"],Y=n;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===W?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=W;}).call(this);
